# Generated by Django 3.2.8 on 2022-03-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220327_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='user_cart', to='main.Pizza'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='volume',
            field=models.IntegerField(default=1),
        ),
    ]
