# Generated by Django 3.2.8 on 2022-03-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='custom_pizzas',
            field=models.ManyToManyField(blank=True, related_name='user_custom_pizzas', to='main.Pizza'),
        ),
    ]
