# Generated by Django 3.2.8 on 2022-03-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_pizza_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='slices',
        ),
        migrations.AddField(
            model_name='pizza',
            name='slices',
            field=models.IntegerField(default=8),
        ),
    ]
